### ISSUE TITLE
FrameReader error while sending messages

### ISSUE THREAD

**Issue by bording** [clearctvm/RabbitMqNext#15]
While trying out RabbitMqNext, I've run into a consistent error. Using the following program:

```csharp
class Program
{
    static void Main(string[] args)
    {
        MainAsync().GetAwaiter().GetResult();
    }

    static async Task MainAsync()
    {
        Console.Title = "Client";
        var numberMessages = 2000000;

        using (var connection = await ConnectionFactory.Connect("rabbit", connectionName: "Client"))
        {
            var channel = await connection.CreateChannel();

            await channel.ExchangeDeclare("Server", "fanout", true, false, null, true);
            await channel.QueueDeclare("Server", false, true, false, false, null, true);
            await channel.QueueBind("Server", "Server", "", null, true);

            for (int i = 0; i < numberMessages; i++)
            {
                var properties = channel.RentBasicProperties();

                var bodyBytes = Encoding.UTF8.GetBytes("This is the message body text");
                var body = new ArraySegment<byte>(bodyBytes);

                await channel.BasicPublish("Server", "", true, properties, body);
            }
        }
    }
}
```

I will let that run and publish messages to a queue that does not have any consumers. Somewhere before it is finished, usually less than half way, I'll see the following error output to the console:
```
Debug [ConnectionIO]: Connected socket to rabbit port 5672
Debug [ConnectionIO]: ReadFramesLoop starting
Debug [ConnectionIO]: WriteFramesLoop starting
Debug [ConnectionIO]: Tune results: Channel max: 0 Frame max size: 131072 heartbeat: 60
Error [FrameReader]: Expecting frame end, but found 13. The original class and method: 10 60
Frame Reader error: System.Exception: Expecting frame end, but found 13. The original class and method: 10 60
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 70
Error [FrameReader]: Frame Reader error System.Exception: Expecting frame end, but found 13. The original class and method: 10 60
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 70
Error [ConnectionIO]: ReadFramesLoop error System.Exception: Expecting frame end, but found 13. The original class and method: 10 60
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 81
   at RabbitMqNext.Io.ConnectionIO.ReadFramesLoop() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 344
Debug [Connection]: Closing all channels
Debug [ConnectionIO]: Socket closed. Stopping loops
Error [ConnectionIO]: WriteFramesLoop exiting

Unhandled Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Channel disposed'.
   at RabbitMqNext.Channel.BasicPublish(String exchange, String routingKey, Boolean mandatory, BasicProperties properties, ArraySegment`1 buffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Channel.cs:line 199
   at Client.Program.<MainAsync>d__1.MoveNext() in C:\Code\RabbitMqNextTest\Client\Program.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Client.Program.Main(String[] args) in C:\Code\RabbitMqNextTest\Client\Program.cs:line 15
```

I have seen this using both 1.0.5 and 1.0.7.

**Comment by hammett** [comment]
So what you see is a connection block sent by the server, but not supported by the client yet. The server is hitting some memory watermark and telling the publishers to stop. There's an open issue to implement this.. I think it's #11

**Comment by bording** [comment]
I saw that issue. Makes sense that it would be related, because I only see it if I don't also have a consumer on the queue.

**Comment by hammett** [comment]
Since this is a dup of an open issue, I'm closing this.
