### ISSUE TITLE
Task returning BasicPublish doesn't play nice with Task.WhenAll

### ISSUE THREAD

**Issue by bording** [clearctvm/RabbitMqNext#16]
When I saw that the `BasicPublish` overloads had been changed to return `Task` instead of `TaskSlim`,  I was hoping that they would work with `Task.WhenAll`, but there seems to be something that isn't quite working correctly.

More specifically, I was hoping to use it with `BasicPublishWithConfirmation` to potentially speed up the sending rate when using publisher confirms. For example:

```csharp
class Program
{
    static void Main(string[] args)
    {
        MainAsync().GetAwaiter().GetResult();
    }

    static async Task MainAsync()
    {
        Console.Title = "Client";
        var numberMessages = 20000;
        var chunkSize = 1000;
        var chunks = numberMessages / chunkSize;

        using (var connection = await ConnectionFactory.Connect("rabbit", connectionName: "Client"))
        {
            var channel = await connection.CreateChannelWithPublishConfirmation(maxunconfirmedMessages: 100);

            await channel.ExchangeDeclare("Server", "fanout", true, false, null, true);
            await channel.QueueDeclare("Server", false, true, false, false, null, true);
            await channel.QueueBind("Server", "Server", "", null, true);

            for (int i = 0; i < chunks; i++)
            {
                var tasks = new List<Task>(chunkSize);

                for (int j = 0; j < chunkSize; j++)
                {
                    var properties = channel.RentBasicProperties();

                    var bodyBytes = Encoding.UTF8.GetBytes("This is the message body text");
                    var body = new ArraySegment<byte>(bodyBytes);

                    var task = channel.BasicPublishWithConfirmation("Server", "", true, properties, body);

                    tasks.Add(task);
                }

                await Task.WhenAll(tasks);
            }
        }
    }
}
```

Doing something like that would hopefully let multiple messages be sent up front, and then I could asynchronously wait for the confirmations after the messages have all been sent. I'm using this technique with the official RabbitMQ client along with some TaskCompletionSources to avoid having to block with WaitForConfirms.

However, when I run this program, the first chunk of messages get sent, and then the program hangs at the `Task.WhenAll` call.

**Comment by hammett** [comment]
Could you try this little experiment in your code? 

`
// await Task.WhenAll(tasks);
foreach(var task in tasks) {
  Console.Writeline(System.Thread.CurrentThread.Name);
  task.Wait();
}
`

Do let me know what shows up. 

Thanks

**Comment by bording** [comment]
I add this to my code:
```csharp
foreach (var task in tasks)
{
	Console.WriteLine($"ThreadName: {System.Threading.Thread.CurrentThread.Name ?? "null"}");
	task.Wait();
}   
```
And I end up getting this output:
```
Debug [ConnectionIO]: Connected socket to rabbit port 5672
Debug [ConnectionIO]: ReadFramesLoop starting
Debug [ConnectionIO]: WriteFramesLoop starting
Debug [ConnectionIO]: Tune results: Channel max: 0 Frame max size: 131072 heartbeat: 60
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
ThreadName: null
Debug [Connection]: Closing all channels
Debug [Amqpq]: Clean close initiated. By server? False
Debug [Amqpq]: Clean close initiated. By server? False
```
It then throws an `AggregateException` with the following `InnerException` message: 
"MessagesPendingConfirmationKeeper: Could not find free spot for the waiting task"

I tried increasing the `maxunconfirmedMessages` value to 1000, and when I do that, it prints two "ThreadName: null" lines and then hangs.

**Comment by hammett** [comment]
Ok, thanks. that confirms it is not running from the framereader thread. I'll look into it soon.

**Comment by bording** [comment]
Finally had some time to try this scenario out again, and I've discovered that there is still something odd going on.

The code as listed in the original post appears to work correctly, however, if I add a `Console.ReadKey` directly after the using statement that disposes the connection, I see the following exception:

```
Error [FrameReader]: Frame Reader error System.Exception: Can't be read since the buffer is in Reset state
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 199
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 62
Error [ConnectionIO]: ReadFramesLoop error System.Exception: Can't be read since the buffer is in Reset state
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 199
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 78
   at RabbitMqNext.Io.ConnectionIO.ReadFramesLoop() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 374
```

On the other hand, if I add the `Console.ReadKey` as the last line just inside the using statement, everything seems to work fine!

Should I open a new issue for this, or is using this one ok? I can't tell if this is a related problem, or if I've come across something new.

**Comment by hammett** [comment]
This is not a bug. After you close a connection I need to set the ringbuffer into a state that it doesnt allow hanging waiting for buffer from the socket or that thread will hang forever. As a consequence, depending on exec state, an attempt to be put in wait will fail with this error.

**Comment by bording** [comment]
> This is not a bug. After you close a connection I need to set the ringbuffer into a state that it doesnt allow hanging waiting for buffer from the socket or that thread will hang forever. As a consequence, depending on exec state, an attempt to be put in wait will fail with this error.

Ok, then if that is expected behavior, why is it displaying it as error? It's non-obvious that this isn't actually a problem.

**Comment by hammett** [comment]
Happy to apply a patch that distinguish a clean connection close from an error situation. Easier said than done.
