### ISSUE TITLE
ExchangeDelete causing server error + forced disconnect

### ISSUE THREAD

**Issue by volak** [clearctvm/RabbitMqNext#20]
I'm working on some tests, which uses ExchangeDelete to cleanly remove subscriptions while testing.  And I'm getting failures due to what seems to be a bad message - heres the logs Im seeing:

``` 
Debug [ConnectionIO]: Connected socket to localhost port 5672 
Debug [ConnectionIO]: WriteFramesLoop starting 
Debug [ConnectionIO]: ReadFramesLoop starting 
Debug [ConnectionIO]: __SendGreeting > 
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (10) payload size: 480 
Debug [FrameReader]: < ConnectionStart PLAIN AMQPLAIN en_US 
Debug [ConnectionIO]: __SendGreeting completed 
Debug [ConnectionIO]: __SendConnectionStartOk > 
Debug [AmqpConnectionFrameWriter]: > ConnectionStartOk 
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (30) payload size: 12 
Debug [FrameReader]: < ConnectionTune: ChannelMax 0 FrameMax 131072 Heartbeat 60 
Debug [ConnectionIO]: __SendConnectionStartOk completed. 
Debug [ConnectionIO]: Tune results: Channel max: 0 Frame max size: 131072 heartbeat: 60 
Debug [ConnectionIO]: __SendConnectionTuneOk > 
Debug [AmqpConnectionFrameWriter]: > ConnectionTuneOk 
Debug [ConnectionIO]: __SendConnectionOpen > vhost / 
Debug [AmqpConnectionFrameWriter]: > ConnectionOpen 
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (41) payload size: 5 
Debug [FrameReader]: < ConnectionOpenOk  
Debug [ConnectionIO]: __SendConnectionOpen completed for vhost / 2016-10-09 19:19:01.736 
INFO  DefaultFactory Logging to 'C:\Users\charl\AppData\Local\NCrunch\23716\5\NServiceBus.RabbitMQ.Tests\bin\Debug' with level Info
Debug [ConnectionIO]: Connected socket to localhost port 5672 
Debug [ConnectionIO]: WriteFramesLoop starting 
Debug [ConnectionIO]: __SendGreeting > 
Debug [ConnectionIO]: ReadFramesLoop starting 
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (10) payload size: 480 
Debug [FrameReader]: < ConnectionStart PLAIN AMQPLAIN en_US 
Debug [ConnectionIO]: __SendGreeting completed 
Debug [ConnectionIO]: __SendConnectionStartOk > 
Debug [AmqpConnectionFrameWriter]: > ConnectionStartOk 
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (30) payload size: 12 
Debug [FrameReader]: < ConnectionTune: ChannelMax 0 FrameMax 131072 Heartbeat 60 
Debug [ConnectionIO]: __SendConnectionStartOk completed. 
Debug [ConnectionIO]: Tune results: Channel max: 0 Frame max size: 131072 heartbeat: 60 
Debug [AmqpConnectionFrameWriter]: > ConnectionTuneOk 
Debug [ConnectionIO]: __SendConnectionTuneOk > 
Debug [ConnectionIO]: __SendConnectionOpen > vhost / 
Debug [AmqpConnectionFrameWriter]: > ConnectionOpen
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (41) payload size: 5 
Debug [FrameReader]: < ConnectionOpenOk  
Debug [ConnectionIO]: __SendConnectionOpen completed for vhost / 
Debug [AmqpChannelLevelFrameWriter]: > ChannelOpen 
Debug [FrameReader]: > Incoming Frame (1) for channel [1] class (20) method  (11) payload size: 8 
Debug [FrameReader]: < ChannelOpenOk  
Debug [AmqpChannelLevelFrameWriter]: > ExchangeDelete testreceiver 
Debug [FrameReader]: > Incoming Frame (1) for channel [0] class (10) method  (50) payload size: 106 
Debug [FrameReader]: < ConnectionClose FRAME_ERROR - cannot decode <<0,0,12,116,101,115,116,114,101,99,101,105,118,101,114,0,0,0,0,0>> in class  40 method 20 
Debug [RecoveryEnabledConnection]: NotifyClosedByServer  
Debug [RecoveryEnabledConnection]: TryInitiateRecovery starting recovery process 
Debug [RecoveryEnabledConnection]: Starting Recovery. Waiting for connection clean up The thread 0x620c has exited with code 0 (0x0).
The thread 0x17c4 has exited with code 0 (0x0).
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Debug [ConnectionIO]: Socket closed. Stopping loops Error [ConnectionIO]: WriteFramesLoop exiting Exception thrown: 'System.Net.Sockets.SocketException' in RabbitMqNext.dll
The thread 0x4ac0 has exited with code 0 (0x0).
Error [FrameReader]: Frame Reader error System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.WriteBufferFromSocketRecv(Socket socket) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 164
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.FillUpBufferFromSocket() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 351
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 207
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 26Exception thrown: 'System.Net.Sockets.SocketException' in RabbitMqNext.dll
Error [ConnectionIO]: ReadFramesLoop error System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.WriteBufferFromSocketRecv(Socket socket) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 164
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.FillUpBufferFromSocket() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 351
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 207
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 78
   at RabbitMqNext.Io.ConnectionIO.ReadFramesLoop() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 374Exception thrown: 'System.Exception' in mscorlib.dll
Exception thrown: 'System.Exception' in mscorlib.dll
Debug [RecoveryEnabledConnection]: NotifyAbrupt System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.WriteBufferFromSocketRecv(Socket socket) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 164
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.FillUpBufferFromSocket() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 351
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 207
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 78
   at RabbitMqNext.Io.ConnectionIO.ReadFramesLoop() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 374Debug [RecoveryEnabledConnection]: NotifyClosedByUser  Debug [Connection]: Closing all channels Debug [AmqpqIOBase]: Clean close initiated. By server? False Debug [RecoveryEnabledConnection]: TryInitiateRecovery: recovery in progress. skipping Debug [ConnectionIO]: __SendConnectionClose > The thread 0x5af8 has exited with code 0 (0x0).
Debug [RecoveryEnabledConnection]: Connection is ready 
```

**Comment by hammett** [comment]
Thanks. I'll take a look soon
