### ISSUE TITLE
Connection recovery question

### ISSUE THREAD

**Issue by ChristianBryanAPC** [clearctvm/RabbitMqNext#22]
Quick question, I have been testing channel recovery using tools like TCPView to terminate the connection and likewise using force close connection option in the RabbitMQ management front end. In the aforementioned cases plus the disconnections I get from our RabbitMQ cluster in AWS, the recovery is fine and my service handles the recovery events and stops/starts itself accordingly. What I do see however is if I physically disconnect the network interface, (throws exception about DNS resolution) I receive the event that it has gone into recovery but once I reconnect the LAN interface no recovery is made and no event is fired, so my service is hanging around waiting for the recovered event. So my question is recovery only limited to connections where DNS resolution is still possible?

**Comment by hammett** [comment]
The recovery process is very simple, it just starts a thread in a loop trying to connect to know hosts, for as long as it takes, unless an unexpected exception happens, and if so it gives up. It does use Dns.GetHostAddresses() too. 

I can't tell why it's behaving that way in your scenario. Could you enable extended logging and post it here?

**Comment by ChristianBryanAPC** [comment]
Ok enabled extended logging:   LogAdapter.ExtendedLogEnabled = true
and configured my service to publish with confirmation, one message every 5 seconds. After the third published message, I yank the network cable and wait for Recovery event to fire, which it does. I then plug the network cable back in, but no recovery is made:

The APCIntegration.Service service is now running, press Control+C to exit.
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 1
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 1
Debug [MessagesPendingConfirmationKeeper]: Confirming delivery 1 lastConfirmed 0  M: False Reque: False isAck: True
Debug [MessagesPendingConfirmationKeeper]: Confirming delivery 1 lastConfirmed 0  M: False Reque: False isAck: True
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 2
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 2
Debug [MessagesPendingConfirmationKeeper]: Confirming delivery 2 lastConfirmed 1  M: False Reque: False isAck: True
Debug [MessagesPendingConfirmationKeeper]: Confirming delivery 2 lastConfirmed 1  M: False Reque: False isAck: True
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 3
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 3
Debug [MessagesPendingConfirmationKeeper]: Confirming delivery 3 lastConfirmed 2  M: False Reque: False isAck: True
Debug [MessagesPendingConfirmationKeeper]: Confirming delivery 3 lastConfirmed 2  M: False Reque: False isAck: True
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 4
Debug [MessagesPendingConfirmationKeeper]: Confirm: took 4
Debug [ConnectionIO]: Socket closed. Stopping loops
Error [ConnectionIO]: WriteFramesLoop exiting
Error [FrameReader]: Frame Reader error System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.WriteBufferFromSocketRecv(Socket socket) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 169
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.FillUpBufferFromSocket() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 351
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 207
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 26
Error [ConnectionIO]: ReadFramesLoop error System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.WriteBufferFromSocketRecv(Socket socket) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 169
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.FillUpBufferFromSocket() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 351
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 207
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 78
   at RabbitMqNext.Io.ConnectionIO.ReadFramesLoop() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 374
Debug [RecoveryEnabledConnection]: NotifyAbrupt System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.WriteBufferFromSocketRecv(Socket socket) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 169
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.FillUpBufferFromSocket() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 351
   at RabbitMqNext.Internals.RingBuffer.ByteRingBuffer.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\ByteRingBuffer.cs:line 207
   at RabbitMqNext.Internals.RingBuffer.RingBufferStreamAdapter.Read(Byte[] buffer, Int32 offset, Int32 count, Boolean fillBuffer) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\RingBuffer\RingBufferStreamAdapter.cs:line 25
   at RabbitMqNext.Internals.InternalBigEndianReader.FillBufferWithLock(Byte[] buffer, Int32 count, Boolean reverse) in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\InternalBigEndianReader.cs:line 28
   at RabbitMqNext.Internals.FrameReader.ReadAndDispatch() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\Protocol\FrameReader.cs:line 78
   at RabbitMqNext.Io.ConnectionIO.ReadFramesLoop() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 374
Debug [RecoveryEnabledConnection]: TryInitiateRecovery starting recovery process
Debug [RecoveryEnabledConnection]: Starting Recovery. Waiting for connection clean up
Debug [RecoveryEnabledConnection]: Connection is ready
Debug [Connection]: Trying to connect to ec2-52-48-201-179.eu-west-1.compute.amazonaws.com
Error [RecoveryEnabledConnection]: TryInitiateRecovery error System.Net.Sockets.SocketException (0x80004005): No such host is known
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at RabbitMqNext.Internals.SocketHolder.<Connect>d__0.MoveNext() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Internals\SocketHolder.cs:line 61
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMqNext.Io.ConnectionIO.<InternalDoConnectSocket>d__7.MoveNext() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Io\ConnectionIO.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMqNext.Connection.<InternalConnect>d__4.MoveNext() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Connection.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMqNext.Recovery.RecoveryEnabledConnection.<CycleReconnect>d__12.MoveNext() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Recovery\RecoveryEnabledConnection.cs:line 255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RabbitMqNext.Recovery.RecoveryEnabledConnection.<<TryInitiateRecovery>b__a>d__c.MoveNext() in c:\dev\clear\RabbitMqNext\src\RabbitMqNext\Recovery\RecoveryEnabledConnection.cs:line 195

**Comment by hammett** [comment]
As I suspected, the issue is with the Dns call. I'll take a look at fixing that soon. Thanks
